[versions]
kotlin = "2.0.0"
agp = "7.3.0"
compose = "1.7.1"
compose-plugin = "1.6.10"
window-styler = "0.3.2"
jna = "5.12.1"
bonsai = "1.2.0"
json = "20220924"
rsyntaxtextarea = "3.3.2"

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
window-styler = { module = "com.mayakapps.compose:window-styler", version.ref = "window-styler" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
bonsai = { module = "cafe.adriel.bonsai:bonsai-core", version.ref = "bonsai" }
bonsai-fileSystem = { module = "cafe.adriel.bonsai:bonsai-file-system", version.ref = "bonsai" }
json = { module = "org.json:json", version.ref = "json" }
rsyntaxtextarea = { module = "com.fifesoft:rsyntaxtextarea", version.ref = "rsyntaxtextarea" } 